<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'TEXT_LOGIN_PLEASE_FILL' => 'To login the system please fill the following fields',
    'TEXT_REQUEST_PASSWORD_RESET_TOKEN_PLEASE_FILL' => 'To request password reset token please fill the following fields',
    'TEXT_RESET_PASSWORD_PLEASE_FILL' => 'To reset password please fill the following fields',
    'TEXT_SIGNUP_PLEASE_FILL' => 'To signup the system please fill the following fields',
    'TITLE_REQUEST_PASSWORD_RESET_TOKEN' => 'Request password reset token',
    'TITLE_RESET_PASSWORD' => 'Reset password',
    'BUTTON_LOGIN' => 'Login',
    'BUTTON_SAVE' => 'Save',
    'BUTTON_SEND' => 'Send',
    'BUTTON_SIGNUP' => 'Singup',
    'NAV_HOME' => 'Home',
    'NAV_LOGIN' => 'Login',
    'NAV_LOGOUT' => 'Logout',
    'NAV_PROFILE' => 'Profile',
    'NAV_SIGNUP' => 'Singup',
    'TITLE_LOGIN' => 'Login',
    'TITLE_PROFILE' => 'Profile',
    'TITLE_SIGNUP' => 'Signup',
];
